# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node Run

on:
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.4]

    steps:
    - uses: actions/checkout@v2
    - name: Node Setup
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Node Start
      run: npm i
      run: npm start
      env:
        TEST_NAME: ${{ secrets.TEST_NAME }}
